// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.6.0 DO NOT EDIT.
package api

import (
	"context"
	"encoding/json"
	"fmt"
	"io"
	"mime/multipart"
	"net/http"

	"github.com/go-chi/chi/v5"
	"github.com/oapi-codegen/runtime"
	strictnethttp "github.com/oapi-codegen/runtime/strictmiddleware/nethttp"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// List all available item types
	// (GET /item-types)
	ListItemTypes(w http.ResponseWriter, r *http.Request)
	// Extract all embedded images from a map file
	// (GET /map/{item_id}/extract)
	ExtractMapImages(w http.ResponseWriter, r *http.Request, itemId openapi_types.UUID)
	// Search indexed items
	// (GET /search)
	SearchItems(w http.ResponseWriter, r *http.Request, params SearchItemsParams)
	// Search items scoped to a single item type
	// (GET /search/{item_type})
	SearchItemsByType(w http.ResponseWriter, r *http.Request, itemType ItemType, params SearchItemsByTypeParams)
	// Upload a new item with metadata
	// (POST /upload/{item_type})
	UploadItem(w http.ResponseWriter, r *http.Request, itemType ItemType)
	// List and filter items of a specific type
	// (GET /{item_type})
	ListItems(w http.ResponseWriter, r *http.Request, itemType ItemType, params ListItemsParams)
	// Download a stored item file
	// (GET /{item_type}/{item_id}/download)
	DownloadItem(w http.ResponseWriter, r *http.Request, itemType ItemType, itemId openapi_types.UUID)
	// Download the thumbnail for an item
	// (GET /{item_type}/{item_id}/thumbnail)
	DownloadThumbnail(w http.ResponseWriter, r *http.Request, itemType ItemType, itemId openapi_types.UUID)
}

// Unimplemented server implementation that returns http.StatusNotImplemented for each endpoint.

type Unimplemented struct{}

// List all available item types
// (GET /item-types)
func (_ Unimplemented) ListItemTypes(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Extract all embedded images from a map file
// (GET /map/{item_id}/extract)
func (_ Unimplemented) ExtractMapImages(w http.ResponseWriter, r *http.Request, itemId openapi_types.UUID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Search indexed items
// (GET /search)
func (_ Unimplemented) SearchItems(w http.ResponseWriter, r *http.Request, params SearchItemsParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Search items scoped to a single item type
// (GET /search/{item_type})
func (_ Unimplemented) SearchItemsByType(w http.ResponseWriter, r *http.Request, itemType ItemType, params SearchItemsByTypeParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Upload a new item with metadata
// (POST /upload/{item_type})
func (_ Unimplemented) UploadItem(w http.ResponseWriter, r *http.Request, itemType ItemType) {
	w.WriteHeader(http.StatusNotImplemented)
}

// List and filter items of a specific type
// (GET /{item_type})
func (_ Unimplemented) ListItems(w http.ResponseWriter, r *http.Request, itemType ItemType, params ListItemsParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Download a stored item file
// (GET /{item_type}/{item_id}/download)
func (_ Unimplemented) DownloadItem(w http.ResponseWriter, r *http.Request, itemType ItemType, itemId openapi_types.UUID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Download the thumbnail for an item
// (GET /{item_type}/{item_id}/thumbnail)
func (_ Unimplemented) DownloadThumbnail(w http.ResponseWriter, r *http.Request, itemType ItemType, itemId openapi_types.UUID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// ListItemTypes operation middleware
func (siw *ServerInterfaceWrapper) ListItemTypes(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListItemTypes(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ExtractMapImages operation middleware
func (siw *ServerInterfaceWrapper) ExtractMapImages(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "item_id" -------------
	var itemId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "item_id", chi.URLParam(r, "item_id"), &itemId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "item_id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ExtractMapImages(w, r, itemId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// SearchItems operation middleware
func (siw *ServerInterfaceWrapper) SearchItems(w http.ResponseWriter, r *http.Request) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params SearchItemsParams

	// ------------- Required query parameter "q" -------------

	if paramValue := r.URL.Query().Get("q"); paramValue != "" {

	} else {
		siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "q"})
		return
	}

	err = runtime.BindQueryParameterWithOptions("form", true, true, "q", r.URL.Query(), &params.Q, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "q", Err: err})
		return
	}

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "limit", r.URL.Query(), &params.Limit, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		return
	}

	// ------------- Optional query parameter "offset" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "offset", r.URL.Query(), &params.Offset, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "offset", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.SearchItems(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// SearchItemsByType operation middleware
func (siw *ServerInterfaceWrapper) SearchItemsByType(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "item_type" -------------
	var itemType ItemType

	err = runtime.BindStyledParameterWithOptions("simple", "item_type", chi.URLParam(r, "item_type"), &itemType, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "item_type", Err: err})
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params SearchItemsByTypeParams

	// ------------- Required query parameter "q" -------------

	if paramValue := r.URL.Query().Get("q"); paramValue != "" {

	} else {
		siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "q"})
		return
	}

	err = runtime.BindQueryParameterWithOptions("form", true, true, "q", r.URL.Query(), &params.Q, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "q", Err: err})
		return
	}

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "limit", r.URL.Query(), &params.Limit, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		return
	}

	// ------------- Optional query parameter "offset" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "offset", r.URL.Query(), &params.Offset, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "offset", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.SearchItemsByType(w, r, itemType, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// UploadItem operation middleware
func (siw *ServerInterfaceWrapper) UploadItem(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "item_type" -------------
	var itemType ItemType

	err = runtime.BindStyledParameterWithOptions("simple", "item_type", chi.URLParam(r, "item_type"), &itemType, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "item_type", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UploadItem(w, r, itemType)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListItems operation middleware
func (siw *ServerInterfaceWrapper) ListItems(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "item_type" -------------
	var itemType ItemType

	err = runtime.BindStyledParameterWithOptions("simple", "item_type", chi.URLParam(r, "item_type"), &itemType, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "item_type", Err: err})
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params ListItemsParams

	// ------------- Optional query parameter "name" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "name", r.URL.Query(), &params.Name, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "name", Err: err})
		return
	}

	// ------------- Optional query parameter "creator" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "creator", r.URL.Query(), &params.Creator, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "creator", Err: err})
		return
	}

	// ------------- Optional query parameter "license" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "license", r.URL.Query(), &params.License, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "license", Err: err})
		return
	}

	// ------------- Optional query parameter "sort" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "sort", r.URL.Query(), &params.Sort, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "sort", Err: err})
		return
	}

	// ------------- Optional query parameter "order" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "order", r.URL.Query(), &params.Order, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "order", Err: err})
		return
	}

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "limit", r.URL.Query(), &params.Limit, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		return
	}

	// ------------- Optional query parameter "offset" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "offset", r.URL.Query(), &params.Offset, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "offset", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListItems(w, r, itemType, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DownloadItem operation middleware
func (siw *ServerInterfaceWrapper) DownloadItem(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "item_type" -------------
	var itemType ItemType

	err = runtime.BindStyledParameterWithOptions("simple", "item_type", chi.URLParam(r, "item_type"), &itemType, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "item_type", Err: err})
		return
	}

	// ------------- Path parameter "item_id" -------------
	var itemId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "item_id", chi.URLParam(r, "item_id"), &itemId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "item_id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DownloadItem(w, r, itemType, itemId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DownloadThumbnail operation middleware
func (siw *ServerInterfaceWrapper) DownloadThumbnail(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "item_type" -------------
	var itemType ItemType

	err = runtime.BindStyledParameterWithOptions("simple", "item_type", chi.URLParam(r, "item_type"), &itemType, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "item_type", Err: err})
		return
	}

	// ------------- Path parameter "item_id" -------------
	var itemId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "item_id", chi.URLParam(r, "item_id"), &itemId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "item_id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DownloadThumbnail(w, r, itemType, itemId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{})
}

type ChiServerOptions struct {
	BaseURL          string
	BaseRouter       chi.Router
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r chi.Router) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r chi.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options ChiServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = chi.NewRouter()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/item-types", wrapper.ListItemTypes)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/map/{item_id}/extract", wrapper.ExtractMapImages)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/search", wrapper.SearchItems)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/search/{item_type}", wrapper.SearchItemsByType)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/upload/{item_type}", wrapper.UploadItem)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/{item_type}", wrapper.ListItems)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/{item_type}/{item_id}/download", wrapper.DownloadItem)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/{item_type}/{item_id}/thumbnail", wrapper.DownloadThumbnail)
	})

	return r
}

type ListItemTypesRequestObject struct {
}

type ListItemTypesResponseObject interface {
	VisitListItemTypesResponse(w http.ResponseWriter) error
}

type ListItemTypes200JSONResponse ItemTypesResponse

func (response ListItemTypes200JSONResponse) VisitListItemTypesResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type ExtractMapImagesRequestObject struct {
	ItemId openapi_types.UUID `json:"item_id"`
}

type ExtractMapImagesResponseObject interface {
	VisitExtractMapImagesResponse(w http.ResponseWriter) error
}

type ExtractMapImages200ApplicationzipResponse struct {
	Body          io.Reader
	ContentLength int64
}

func (response ExtractMapImages200ApplicationzipResponse) VisitExtractMapImagesResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/zip")
	if response.ContentLength != 0 {
		w.Header().Set("Content-Length", fmt.Sprint(response.ContentLength))
	}
	w.WriteHeader(200)

	if closer, ok := response.Body.(io.ReadCloser); ok {
		defer closer.Close()
	}
	_, err := io.Copy(w, response.Body)
	return err
}

type ExtractMapImages404JSONResponse ErrorResponse

func (response ExtractMapImages404JSONResponse) VisitExtractMapImagesResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type ExtractMapImages500JSONResponse ErrorResponse

func (response ExtractMapImages500JSONResponse) VisitExtractMapImagesResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type SearchItemsRequestObject struct {
	Params SearchItemsParams
}

type SearchItemsResponseObject interface {
	VisitSearchItemsResponse(w http.ResponseWriter) error
}

type SearchItems200JSONResponse SearchResponse

func (response SearchItems200JSONResponse) VisitSearchItemsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type SearchItems400JSONResponse ErrorResponse

func (response SearchItems400JSONResponse) VisitSearchItemsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type SearchItems500JSONResponse ErrorResponse

func (response SearchItems500JSONResponse) VisitSearchItemsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type SearchItemsByTypeRequestObject struct {
	ItemType ItemType `json:"item_type"`
	Params   SearchItemsByTypeParams
}

type SearchItemsByTypeResponseObject interface {
	VisitSearchItemsByTypeResponse(w http.ResponseWriter) error
}

type SearchItemsByType200JSONResponse SearchResponse

func (response SearchItemsByType200JSONResponse) VisitSearchItemsByTypeResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type SearchItemsByType400JSONResponse ErrorResponse

func (response SearchItemsByType400JSONResponse) VisitSearchItemsByTypeResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type SearchItemsByType500JSONResponse ErrorResponse

func (response SearchItemsByType500JSONResponse) VisitSearchItemsByTypeResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type UploadItemRequestObject struct {
	ItemType ItemType `json:"item_type"`
	Body     *multipart.Reader
}

type UploadItemResponseObject interface {
	VisitUploadItemResponse(w http.ResponseWriter) error
}

type UploadItem201JSONResponse UploadResponse

func (response UploadItem201JSONResponse) VisitUploadItemResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)

	return json.NewEncoder(w).Encode(response)
}

type UploadItem400JSONResponse ErrorResponse

func (response UploadItem400JSONResponse) VisitUploadItemResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type UploadItem409JSONResponse ErrorResponse

func (response UploadItem409JSONResponse) VisitUploadItemResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(409)

	return json.NewEncoder(w).Encode(response)
}

type UploadItem500JSONResponse ErrorResponse

func (response UploadItem500JSONResponse) VisitUploadItemResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type UploadItem507JSONResponse ErrorResponse

func (response UploadItem507JSONResponse) VisitUploadItemResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(507)

	return json.NewEncoder(w).Encode(response)
}

type ListItemsRequestObject struct {
	ItemType ItemType `json:"item_type"`
	Params   ListItemsParams
}

type ListItemsResponseObject interface {
	VisitListItemsResponse(w http.ResponseWriter) error
}

type ListItems200JSONResponse ListItemsResponse

func (response ListItems200JSONResponse) VisitListItemsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type ListItems400JSONResponse ErrorResponse

func (response ListItems400JSONResponse) VisitListItemsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type ListItems500JSONResponse ErrorResponse

func (response ListItems500JSONResponse) VisitListItemsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type DownloadItemRequestObject struct {
	ItemType ItemType           `json:"item_type"`
	ItemId   openapi_types.UUID `json:"item_id"`
}

type DownloadItemResponseObject interface {
	VisitDownloadItemResponse(w http.ResponseWriter) error
}

type DownloadItem200ApplicationoctetStreamResponse struct {
	Body          io.Reader
	ContentLength int64
}

func (response DownloadItem200ApplicationoctetStreamResponse) VisitDownloadItemResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/octet-stream")
	if response.ContentLength != 0 {
		w.Header().Set("Content-Length", fmt.Sprint(response.ContentLength))
	}
	w.WriteHeader(200)

	if closer, ok := response.Body.(io.ReadCloser); ok {
		defer closer.Close()
	}
	_, err := io.Copy(w, response.Body)
	return err
}

type DownloadItem404JSONResponse ErrorResponse

func (response DownloadItem404JSONResponse) VisitDownloadItemResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type DownloadItem500JSONResponse ErrorResponse

func (response DownloadItem500JSONResponse) VisitDownloadItemResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type DownloadThumbnailRequestObject struct {
	ItemType ItemType           `json:"item_type"`
	ItemId   openapi_types.UUID `json:"item_id"`
}

type DownloadThumbnailResponseObject interface {
	VisitDownloadThumbnailResponse(w http.ResponseWriter) error
}

type DownloadThumbnail200ImagepngResponse struct {
	Body          io.Reader
	ContentLength int64
}

func (response DownloadThumbnail200ImagepngResponse) VisitDownloadThumbnailResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "image/png")
	if response.ContentLength != 0 {
		w.Header().Set("Content-Length", fmt.Sprint(response.ContentLength))
	}
	w.WriteHeader(200)

	if closer, ok := response.Body.(io.ReadCloser); ok {
		defer closer.Close()
	}
	_, err := io.Copy(w, response.Body)
	return err
}

type DownloadThumbnail404JSONResponse ErrorResponse

func (response DownloadThumbnail404JSONResponse) VisitDownloadThumbnailResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type DownloadThumbnail500JSONResponse ErrorResponse

func (response DownloadThumbnail500JSONResponse) VisitDownloadThumbnailResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// List all available item types
	// (GET /item-types)
	ListItemTypes(ctx context.Context, request ListItemTypesRequestObject) (ListItemTypesResponseObject, error)
	// Extract all embedded images from a map file
	// (GET /map/{item_id}/extract)
	ExtractMapImages(ctx context.Context, request ExtractMapImagesRequestObject) (ExtractMapImagesResponseObject, error)
	// Search indexed items
	// (GET /search)
	SearchItems(ctx context.Context, request SearchItemsRequestObject) (SearchItemsResponseObject, error)
	// Search items scoped to a single item type
	// (GET /search/{item_type})
	SearchItemsByType(ctx context.Context, request SearchItemsByTypeRequestObject) (SearchItemsByTypeResponseObject, error)
	// Upload a new item with metadata
	// (POST /upload/{item_type})
	UploadItem(ctx context.Context, request UploadItemRequestObject) (UploadItemResponseObject, error)
	// List and filter items of a specific type
	// (GET /{item_type})
	ListItems(ctx context.Context, request ListItemsRequestObject) (ListItemsResponseObject, error)
	// Download a stored item file
	// (GET /{item_type}/{item_id}/download)
	DownloadItem(ctx context.Context, request DownloadItemRequestObject) (DownloadItemResponseObject, error)
	// Download the thumbnail for an item
	// (GET /{item_type}/{item_id}/thumbnail)
	DownloadThumbnail(ctx context.Context, request DownloadThumbnailRequestObject) (DownloadThumbnailResponseObject, error)
}

type StrictHandlerFunc = strictnethttp.StrictHTTPHandlerFunc
type StrictMiddlewareFunc = strictnethttp.StrictHTTPMiddlewareFunc

type StrictHTTPServerOptions struct {
	RequestErrorHandlerFunc  func(w http.ResponseWriter, r *http.Request, err error)
	ResponseErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: StrictHTTPServerOptions{
		RequestErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		},
		ResponseErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		},
	}}
}

func NewStrictHandlerWithOptions(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc, options StrictHTTPServerOptions) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: options}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
	options     StrictHTTPServerOptions
}

// ListItemTypes operation middleware
func (sh *strictHandler) ListItemTypes(w http.ResponseWriter, r *http.Request) {
	var request ListItemTypesRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ListItemTypes(ctx, request.(ListItemTypesRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListItemTypes")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ListItemTypesResponseObject); ok {
		if err := validResponse.VisitListItemTypesResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// ExtractMapImages operation middleware
func (sh *strictHandler) ExtractMapImages(w http.ResponseWriter, r *http.Request, itemId openapi_types.UUID) {
	var request ExtractMapImagesRequestObject

	request.ItemId = itemId

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ExtractMapImages(ctx, request.(ExtractMapImagesRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ExtractMapImages")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ExtractMapImagesResponseObject); ok {
		if err := validResponse.VisitExtractMapImagesResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// SearchItems operation middleware
func (sh *strictHandler) SearchItems(w http.ResponseWriter, r *http.Request, params SearchItemsParams) {
	var request SearchItemsRequestObject

	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.SearchItems(ctx, request.(SearchItemsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "SearchItems")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(SearchItemsResponseObject); ok {
		if err := validResponse.VisitSearchItemsResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// SearchItemsByType operation middleware
func (sh *strictHandler) SearchItemsByType(w http.ResponseWriter, r *http.Request, itemType ItemType, params SearchItemsByTypeParams) {
	var request SearchItemsByTypeRequestObject

	request.ItemType = itemType
	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.SearchItemsByType(ctx, request.(SearchItemsByTypeRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "SearchItemsByType")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(SearchItemsByTypeResponseObject); ok {
		if err := validResponse.VisitSearchItemsByTypeResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// UploadItem operation middleware
func (sh *strictHandler) UploadItem(w http.ResponseWriter, r *http.Request, itemType ItemType) {
	var request UploadItemRequestObject

	request.ItemType = itemType

	if reader, err := r.MultipartReader(); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode multipart body: %w", err))
		return
	} else {
		request.Body = reader
	}

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.UploadItem(ctx, request.(UploadItemRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "UploadItem")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(UploadItemResponseObject); ok {
		if err := validResponse.VisitUploadItemResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// ListItems operation middleware
func (sh *strictHandler) ListItems(w http.ResponseWriter, r *http.Request, itemType ItemType, params ListItemsParams) {
	var request ListItemsRequestObject

	request.ItemType = itemType
	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ListItems(ctx, request.(ListItemsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListItems")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ListItemsResponseObject); ok {
		if err := validResponse.VisitListItemsResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// DownloadItem operation middleware
func (sh *strictHandler) DownloadItem(w http.ResponseWriter, r *http.Request, itemType ItemType, itemId openapi_types.UUID) {
	var request DownloadItemRequestObject

	request.ItemType = itemType
	request.ItemId = itemId

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.DownloadItem(ctx, request.(DownloadItemRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "DownloadItem")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(DownloadItemResponseObject); ok {
		if err := validResponse.VisitDownloadItemResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// DownloadThumbnail operation middleware
func (sh *strictHandler) DownloadThumbnail(w http.ResponseWriter, r *http.Request, itemType ItemType, itemId openapi_types.UUID) {
	var request DownloadThumbnailRequestObject

	request.ItemType = itemType
	request.ItemId = itemId

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.DownloadThumbnail(ctx, request.(DownloadThumbnailRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "DownloadThumbnail")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(DownloadThumbnailResponseObject); ok {
		if err := validResponse.VisitDownloadThumbnailResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}
