// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.6.0 DO NOT EDIT.
package api

import (
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for ItemType.
const (
	Emoticon ItemType = "emoticon"
	Entity   ItemType = "entity"
	Gameskin ItemType = "gameskin"
	Hud      ItemType = "hud"
	Map      ItemType = "map"
	Skin     ItemType = "skin"
	Template ItemType = "template"
	Theme    ItemType = "theme"
)

// Valid indicates whether the value is a known member of the ItemType enum.
func (e ItemType) Valid() bool {
	switch e {
	case Emoticon:
		return true
	case Entity:
		return true
	case Gameskin:
		return true
	case Hud:
		return true
	case Map:
		return true
	case Skin:
		return true
	case Template:
		return true
	case Theme:
		return true
	default:
		return false
	}
}

// Defines values for License.
const (
	Cc0      License = "cc0"
	CcBy     License = "cc-by"
	CcByNc   License = "cc-by-nc"
	CcByNcNd License = "cc-by-nc-nd"
	CcByNcSa License = "cc-by-nc-sa"
	CcByNd   License = "cc-by-nd"
	CcBySa   License = "cc-by-sa"
	Custom   License = "custom"
	Gpl2     License = "gpl-2"
	Gpl3     License = "gpl-3"
	Mit      License = "mit"
	Unknown  License = "unknown"
)

// Valid indicates whether the value is a known member of the License enum.
func (e License) Valid() bool {
	switch e {
	case Cc0:
		return true
	case CcBy:
		return true
	case CcByNc:
		return true
	case CcByNcNd:
		return true
	case CcByNcSa:
		return true
	case CcByNd:
		return true
	case CcBySa:
		return true
	case Custom:
		return true
	case Gpl2:
		return true
	case Gpl3:
		return true
	case Mit:
		return true
	case Unknown:
		return true
	default:
		return false
	}
}

// Defines values for SortField.
const (
	CreatedAt SortField = "created_at"
	Name      SortField = "name"
)

// Valid indicates whether the value is a known member of the SortField enum.
func (e SortField) Valid() bool {
	switch e {
	case CreatedAt:
		return true
	case Name:
		return true
	default:
		return false
	}
}

// Defines values for SortOrder.
const (
	Asc  SortOrder = "asc"
	Desc SortOrder = "desc"
)

// Valid indicates whether the value is a known member of the SortOrder enum.
func (e SortOrder) Valid() bool {
	switch e {
	case Asc:
		return true
	case Desc:
		return true
	default:
		return false
	}
}

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	// Error Human-readable error message.
	Error string `json:"error"`
}

// ItemMetadata defines model for ItemMetadata.
type ItemMetadata struct {
	// Creators List of creator names.
	Creators []string `json:"creators"`

	// License Content license. Supported values:
	// - cc0          – Creative Commons Zero (public domain dedication)
	// - cc-by        – CC Attribution
	// - cc-by-sa     – CC Attribution-ShareAlike
	// - cc-by-nd     – CC Attribution-NoDerivs
	// - cc-by-nc     – CC Attribution-NonCommercial
	// - cc-by-nc-sa  – CC Attribution-NonCommercial-ShareAlike
	// - cc-by-nc-nd  – CC Attribution-NonCommercial-NoDerivs
	// - gpl-2        – GNU General Public License v2
	// - gpl-3        – GNU General Public License v3
	// - mit          – MIT License
	// - custom       – Custom / other known license
	// - unknown      – License not specified
	License License `json:"license"`

	// Name Human-readable name of the item.
	Name string `json:"name"`
}

// ItemType defines model for ItemType.
type ItemType string

// ItemTypesResponse defines model for ItemTypesResponse.
type ItemTypesResponse struct {
	// AssetTypes All available item types.
	AssetTypes []ItemType `json:"asset_types"`
}

// License Content license. Supported values:
// - cc0          – Creative Commons Zero (public domain dedication)
// - cc-by        – CC Attribution
// - cc-by-sa     – CC Attribution-ShareAlike
// - cc-by-nd     – CC Attribution-NoDerivs
// - cc-by-nc     – CC Attribution-NonCommercial
// - cc-by-nc-sa  – CC Attribution-NonCommercial-ShareAlike
// - cc-by-nc-nd  – CC Attribution-NonCommercial-NoDerivs
// - gpl-2        – GNU General Public License v2
// - gpl-3        – GNU General Public License v3
// - mit          – MIT License
// - custom       – Custom / other known license
// - unknown      – License not specified
type License string

// ListItem defines model for ListItem.
type ListItem struct {
	AssetType ItemType `json:"asset_type"`

	// ItemId Unique identifier of the item.
	ItemId openapi_types.UUID `json:"item_id"`

	// ItemValue Arbitrary JSON payload of the item.
	ItemValue map[string]interface{} `json:"item_value"`
}

// ListItemsResponse defines model for ListItemsResponse.
type ListItemsResponse struct {
	Results []ListItem `json:"results"`

	// Total Total number of results before pagination.
	Total int `json:"total"`
}

// MultiBundleRequest defines model for MultiBundleRequest.
type MultiBundleRequest struct {
	// GroupIds List of asset group IDs to include in the ZIP archive.
	GroupIds []openapi_types.UUID `json:"group_ids"`
}

// SearchResponse defines model for SearchResponse.
type SearchResponse struct {
	Results []SearchResult `json:"results"`

	// Total Total number of results before pagination.
	Total int `json:"total"`
}

// SearchResult defines model for SearchResult.
type SearchResult struct {
	AssetType ItemType `json:"asset_type"`

	// ItemId Unique identifier of the item.
	ItemId openapi_types.UUID `json:"item_id"`

	// ItemValue Arbitrary JSON payload of the item.
	ItemValue map[string]interface{} `json:"item_value"`

	// Score Relevance score (higher is better).
	Score float64 `json:"score"`
}

// SortField Field to sort results by.
type SortField string

// SortOrder Sort direction.
type SortOrder string

// UploadResponse defines model for UploadResponse.
type UploadResponse struct {
	// ItemId Server-assigned identifier of the newly created item.
	ItemId openapi_types.UUID `json:"item_id"`
}

// SearchItemsParams defines parameters for SearchItems.
type SearchItemsParams struct {
	// Q Search query string.
	Q string `form:"q" json:"q"`

	// Limit Maximum number of results to return (default 20, max 100).
	Limit *int `form:"limit,omitempty" json:"limit,omitempty"`

	// Offset Number of results to skip for pagination (default 0).
	Offset *int `form:"offset,omitempty" json:"offset,omitempty"`
}

// SearchItemsByTypeParams defines parameters for SearchItemsByType.
type SearchItemsByTypeParams struct {
	// Q Search query string.
	Q string `form:"q" json:"q"`

	// Limit Maximum number of results to return (default 100, max 1000).
	Limit *int `form:"limit,omitempty" json:"limit,omitempty"`

	// Offset Number of results to skip for pagination (default 0).
	Offset *int `form:"offset,omitempty" json:"offset,omitempty"`
}

// UploadItemMultipartBody defines parameters for UploadItem.
type UploadItemMultipartBody struct {
	File     openapi_types.File `json:"file"`
	Metadata ItemMetadata       `json:"metadata"`
}

// ListItemsParams defines parameters for ListItems.
type ListItemsParams struct {
	// Name Filter by item name (case-insensitive substring match).
	Name *string `form:"name,omitempty" json:"name,omitempty"`

	// Creator Filter by creator name (case-insensitive substring match).
	Creator *string `form:"creator,omitempty" json:"creator,omitempty"`

	// License Filter by exact license value.
	License *License `form:"license,omitempty" json:"license,omitempty"`

	// Sort Field to sort by (default "name").
	Sort *SortField `form:"sort,omitempty" json:"sort,omitempty"`

	// Order Sort direction (default "asc").
	Order *SortOrder `form:"order,omitempty" json:"order,omitempty"`

	// Limit Maximum number of results to return (default 100, max 1000).
	Limit *int `form:"limit,omitempty" json:"limit,omitempty"`

	// Offset Number of results to skip for pagination (default 0).
	Offset *int `form:"offset,omitempty" json:"offset,omitempty"`
}

// DownloadThumbnailParams defines parameters for DownloadThumbnail.
type DownloadThumbnailParams struct {
	// IfNoneMatch ETag value from a previous response. If the thumbnail has not changed, the server responds with 304 Not Modified.
	IfNoneMatch *string `json:"If-None-Match,omitempty"`
}

// RenderItemListParams defines parameters for RenderItemList.
type RenderItemListParams struct {
	// Q Optional fuzzy search query.
	Q *string `form:"q,omitempty" json:"q,omitempty"`

	// Limit Maximum number of results (default 100, max 1000).
	Limit *int `form:"limit,omitempty" json:"limit,omitempty"`

	// Offset Pagination offset (default 0).
	Offset *int `form:"offset,omitempty" json:"offset,omitempty"`

	// Sort Comma-separated list of sort directives, each in the form "field:asc" or "field:desc". Supported fields are name and created_at. Example: "name:asc,created_at:desc".
	Sort *string `form:"sort,omitempty" json:"sort,omitempty"`

	// Creator Filter results to items with exactly this creator.
	Creator *string `form:"creator,omitempty" json:"creator,omitempty"`

	// License Filter results to items with exactly this license.
	License *string `form:"license,omitempty" json:"license,omitempty"`

	// Date Filter results to items created on this date (YYYY-MM-DD).
	Date *string `form:"date,omitempty" json:"date,omitempty"`
}

// DownloadMultiBundleJSONRequestBody defines body for DownloadMultiBundle for application/json ContentType.
type DownloadMultiBundleJSONRequestBody = MultiBundleRequest

// UploadItemMultipartRequestBody defines body for UploadItem for multipart/form-data ContentType.
type UploadItemMultipartRequestBody UploadItemMultipartBody
