// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: admin.sql

package sql

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const countGroupItems = `-- name: CountGroupItems :one
SELECT COUNT(*) FROM asset_item WHERE group_id = $1
`

func (q *Queries) CountGroupItems(ctx context.Context, groupID uuid.UUID) (int64, error) {
	row := q.queryRow(ctx, q.countGroupItemsStmt, countGroupItems, groupID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteGroup = `-- name: DeleteGroup :exec
DELETE FROM asset_group
WHERE group_id = $1
AND   asset_type = $2
`

type DeleteGroupParams struct {
	GroupID   uuid.UUID     `db:"group_id"`
	AssetType AssetTypeEnum `db:"asset_type"`
}

func (q *Queries) DeleteGroup(ctx context.Context, arg DeleteGroupParams) error {
	_, err := q.exec(ctx, q.deleteGroupStmt, deleteGroup, arg.GroupID, arg.AssetType)
	return err
}

const deleteItem = `-- name: DeleteItem :exec
DELETE FROM asset_item
WHERE item_id   = $1
AND   group_id  = $2
`

type DeleteItemParams struct {
	ItemID  uuid.UUID `db:"item_id"`
	GroupID uuid.UUID `db:"group_id"`
}

func (q *Queries) DeleteItem(ctx context.Context, arg DeleteItemParams) error {
	_, err := q.exec(ctx, q.deleteItemStmt, deleteItem, arg.ItemID, arg.GroupID)
	return err
}

const deleteSearchValues = `-- name: DeleteSearchValues :exec
DELETE FROM search_value
WHERE group_id = $1
AND   key_name = $2
`

type DeleteSearchValuesParams struct {
	GroupID uuid.UUID `db:"group_id"`
	KeyName string    `db:"key_name"`
}

func (q *Queries) DeleteSearchValues(ctx context.Context, arg DeleteSearchValuesParams) error {
	_, err := q.exec(ctx, q.deleteSearchValuesStmt, deleteSearchValues, arg.GroupID, arg.KeyName)
	return err
}

const getGroupInfo = `-- name: GetGroupInfo :one
SELECT ag.group_id, ag.asset_type, ag.group_name, ag.group_key
FROM   asset_group ag
WHERE  ag.group_id  = $1
AND    ag.asset_type = $2
`

type GetGroupInfoParams struct {
	GroupID   uuid.UUID     `db:"group_id"`
	AssetType AssetTypeEnum `db:"asset_type"`
}

func (q *Queries) GetGroupInfo(ctx context.Context, arg GetGroupInfoParams) (AssetGroup, error) {
	row := q.queryRow(ctx, q.getGroupInfoStmt, getGroupInfo, arg.GroupID, arg.AssetType)
	var i AssetGroup
	err := row.Scan(
		&i.GroupID,
		&i.AssetType,
		&i.GroupName,
		&i.GroupKey,
	)
	return i, err
}

const getGroupItemPaths = `-- name: GetGroupItemPaths :many
SELECT ai.item_file_path, ai.item_thumbnail_path
FROM   asset_item ai
WHERE  ai.group_id = $1
`

type GetGroupItemPathsRow struct {
	ItemFilePath      string         `db:"item_file_path"`
	ItemThumbnailPath sql.NullString `db:"item_thumbnail_path"`
}

func (q *Queries) GetGroupItemPaths(ctx context.Context, groupID uuid.UUID) ([]GetGroupItemPathsRow, error) {
	rows, err := q.query(ctx, q.getGroupItemPathsStmt, getGroupItemPaths, groupID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetGroupItemPathsRow{}
	for rows.Next() {
		var i GetGroupItemPathsRow
		if err := rows.Scan(&i.ItemFilePath, &i.ItemThumbnailPath); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getGroupItems = `-- name: GetGroupItems :many
SELECT ai.item_id,
       ai.group_value,
       ai.size,
       ai.original_filename
FROM   asset_item ai
WHERE  ai.group_id = $1
ORDER  BY ai.group_value
`

type GetGroupItemsRow struct {
	ItemID           uuid.UUID `db:"item_id"`
	GroupValue       string    `db:"group_value"`
	Size             int64     `db:"size"`
	OriginalFilename string    `db:"original_filename"`
}

func (q *Queries) GetGroupItems(ctx context.Context, groupID uuid.UUID) ([]GetGroupItemsRow, error) {
	rows, err := q.query(ctx, q.getGroupItemsStmt, getGroupItems, groupID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetGroupItemsRow{}
	for rows.Next() {
		var i GetGroupItemsRow
		if err := rows.Scan(
			&i.ItemID,
			&i.GroupValue,
			&i.Size,
			&i.OriginalFilename,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getGroupItemsWithMetadata = `-- name: GetGroupItemsWithMetadata :many
SELECT ai.item_id,
       ai.group_value,
       ai.size,
       ai.original_filename,
       aim.created_at,
       host(aim.creator_ip)::TEXT AS creator_ip,
       aim.creator_agent,
       aim.accept_language,
       aim.referer,
       aim.content_type,
       aim.request_id
FROM   asset_item ai
JOIN   asset_item_metadata aim ON aim.item_id = ai.item_id
WHERE  ai.group_id = $1
ORDER  BY ai.group_value
`

type GetGroupItemsWithMetadataRow struct {
	ItemID           uuid.UUID `db:"item_id"`
	GroupValue       string    `db:"group_value"`
	Size             int64     `db:"size"`
	OriginalFilename string    `db:"original_filename"`
	CreatedAt        time.Time `db:"created_at"`
	CreatorIp        string    `db:"creator_ip"`
	CreatorAgent     string    `db:"creator_agent"`
	AcceptLanguage   string    `db:"accept_language"`
	Referer          string    `db:"referer"`
	ContentType      string    `db:"content_type"`
	RequestID        string    `db:"request_id"`
}

func (q *Queries) GetGroupItemsWithMetadata(ctx context.Context, groupID uuid.UUID) ([]GetGroupItemsWithMetadataRow, error) {
	rows, err := q.query(ctx, q.getGroupItemsWithMetadataStmt, getGroupItemsWithMetadata, groupID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetGroupItemsWithMetadataRow{}
	for rows.Next() {
		var i GetGroupItemsWithMetadataRow
		if err := rows.Scan(
			&i.ItemID,
			&i.GroupValue,
			&i.Size,
			&i.OriginalFilename,
			&i.CreatedAt,
			&i.CreatorIp,
			&i.CreatorAgent,
			&i.AcceptLanguage,
			&i.Referer,
			&i.ContentType,
			&i.RequestID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getItemInfo = `-- name: GetItemInfo :one
SELECT ai.item_id, ai.group_id, ai.group_value, ai.size, ai.item_file_path, ai.item_thumbnail_path
FROM   asset_item ai
WHERE  ai.item_id  = $1
AND    ai.group_id = $2
`

type GetItemInfoParams struct {
	ItemID  uuid.UUID `db:"item_id"`
	GroupID uuid.UUID `db:"group_id"`
}

type GetItemInfoRow struct {
	ItemID            uuid.UUID      `db:"item_id"`
	GroupID           uuid.UUID      `db:"group_id"`
	GroupValue        string         `db:"group_value"`
	Size              int64          `db:"size"`
	ItemFilePath      string         `db:"item_file_path"`
	ItemThumbnailPath sql.NullString `db:"item_thumbnail_path"`
}

func (q *Queries) GetItemInfo(ctx context.Context, arg GetItemInfoParams) (GetItemInfoRow, error) {
	row := q.queryRow(ctx, q.getItemInfoStmt, getItemInfo, arg.ItemID, arg.GroupID)
	var i GetItemInfoRow
	err := row.Scan(
		&i.ItemID,
		&i.GroupID,
		&i.GroupValue,
		&i.Size,
		&i.ItemFilePath,
		&i.ItemThumbnailPath,
	)
	return i, err
}

const updateGroupName = `-- name: UpdateGroupName :exec
UPDATE asset_group
SET    group_name = $1
WHERE  group_id   = $2
AND    asset_type = $3
`

type UpdateGroupNameParams struct {
	GroupName string        `db:"group_name"`
	GroupID   uuid.UUID     `db:"group_id"`
	AssetType AssetTypeEnum `db:"asset_type"`
}

func (q *Queries) UpdateGroupName(ctx context.Context, arg UpdateGroupNameParams) error {
	_, err := q.exec(ctx, q.updateGroupNameStmt, updateGroupName, arg.GroupName, arg.GroupID, arg.AssetType)
	return err
}

const updateItem = `-- name: UpdateItem :exec
UPDATE asset_item
SET    size              = $1,
       checksum          = $2,
       item_file_path    = $3,
       item_thumbnail_path = $7,
       original_filename = $4
WHERE  item_id  = $5
AND    group_id = $6
`

type UpdateItemParams struct {
	Size              int64          `db:"size"`
	Checksum          string         `db:"checksum"`
	ItemFilePath      string         `db:"item_file_path"`
	OriginalFilename  string         `db:"original_filename"`
	ItemID            uuid.UUID      `db:"item_id"`
	GroupID           uuid.UUID      `db:"group_id"`
	ItemThumbnailPath sql.NullString `db:"item_thumbnail_path"`
}

func (q *Queries) UpdateItem(ctx context.Context, arg UpdateItemParams) error {
	_, err := q.exec(ctx, q.updateItemStmt, updateItem,
		arg.Size,
		arg.Checksum,
		arg.ItemFilePath,
		arg.OriginalFilename,
		arg.ItemID,
		arg.GroupID,
		arg.ItemThumbnailPath,
	)
	return err
}
