// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sql

import (
	"context"
	"database/sql"
	"fmt"
)

type DBTX interface {
	ExecContext(context.Context, string, ...interface{}) (sql.Result, error)
	PrepareContext(context.Context, string) (*sql.Stmt, error)
	QueryContext(context.Context, string, ...interface{}) (*sql.Rows, error)
	QueryRowContext(context.Context, string, ...interface{}) *sql.Row
}

func New(db DBTX) *Queries {
	return &Queries{db: db}
}

func Prepare(ctx context.Context, db DBTX) (*Queries, error) {
	q := Queries{db: db}
	var err error
	if q.getItemFilePathStmt, err = db.PrepareContext(ctx, getItemFilePath); err != nil {
		return nil, fmt.Errorf("error preparing query GetItemFilePath: %w", err)
	}
	if q.getItemThumbnailPathStmt, err = db.PrepareContext(ctx, getItemThumbnailPath); err != nil {
		return nil, fmt.Errorf("error preparing query GetItemThumbnailPath: %w", err)
	}
	if q.insertItemStmt, err = db.PrepareContext(ctx, insertItem); err != nil {
		return nil, fmt.Errorf("error preparing query InsertItem: %w", err)
	}
	if q.insertItemMetadataStmt, err = db.PrepareContext(ctx, insertItemMetadata); err != nil {
		return nil, fmt.Errorf("error preparing query InsertItemMetadata: %w", err)
	}
	if q.insertSearchValueStmt, err = db.PrepareContext(ctx, insertSearchValue); err != nil {
		return nil, fmt.Errorf("error preparing query InsertSearchValue: %w", err)
	}
	if q.listItemsStmt, err = db.PrepareContext(ctx, listItems); err != nil {
		return nil, fmt.Errorf("error preparing query ListItems: %w", err)
	}
	if q.searchStmt, err = db.PrepareContext(ctx, search); err != nil {
		return nil, fmt.Errorf("error preparing query Search: %w", err)
	}
	if q.searchByTypeStmt, err = db.PrepareContext(ctx, searchByType); err != nil {
		return nil, fmt.Errorf("error preparing query SearchByType: %w", err)
	}
	return &q, nil
}

func (q *Queries) Close() error {
	var err error
	if q.getItemFilePathStmt != nil {
		if cerr := q.getItemFilePathStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getItemFilePathStmt: %w", cerr)
		}
	}
	if q.getItemThumbnailPathStmt != nil {
		if cerr := q.getItemThumbnailPathStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getItemThumbnailPathStmt: %w", cerr)
		}
	}
	if q.insertItemStmt != nil {
		if cerr := q.insertItemStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing insertItemStmt: %w", cerr)
		}
	}
	if q.insertItemMetadataStmt != nil {
		if cerr := q.insertItemMetadataStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing insertItemMetadataStmt: %w", cerr)
		}
	}
	if q.insertSearchValueStmt != nil {
		if cerr := q.insertSearchValueStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing insertSearchValueStmt: %w", cerr)
		}
	}
	if q.listItemsStmt != nil {
		if cerr := q.listItemsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listItemsStmt: %w", cerr)
		}
	}
	if q.searchStmt != nil {
		if cerr := q.searchStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing searchStmt: %w", cerr)
		}
	}
	if q.searchByTypeStmt != nil {
		if cerr := q.searchByTypeStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing searchByTypeStmt: %w", cerr)
		}
	}
	return err
}

func (q *Queries) exec(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) (sql.Result, error) {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).ExecContext(ctx, args...)
	case stmt != nil:
		return stmt.ExecContext(ctx, args...)
	default:
		return q.db.ExecContext(ctx, query, args...)
	}
}

func (q *Queries) query(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) (*sql.Rows, error) {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).QueryContext(ctx, args...)
	case stmt != nil:
		return stmt.QueryContext(ctx, args...)
	default:
		return q.db.QueryContext(ctx, query, args...)
	}
}

func (q *Queries) queryRow(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) *sql.Row {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).QueryRowContext(ctx, args...)
	case stmt != nil:
		return stmt.QueryRowContext(ctx, args...)
	default:
		return q.db.QueryRowContext(ctx, query, args...)
	}
}

type Queries struct {
	db                       DBTX
	tx                       *sql.Tx
	getItemFilePathStmt      *sql.Stmt
	getItemThumbnailPathStmt *sql.Stmt
	insertItemStmt           *sql.Stmt
	insertItemMetadataStmt   *sql.Stmt
	insertSearchValueStmt    *sql.Stmt
	listItemsStmt            *sql.Stmt
	searchStmt               *sql.Stmt
	searchByTypeStmt         *sql.Stmt
}

func (q *Queries) WithTx(tx *sql.Tx) *Queries {
	return &Queries{
		db:                       tx,
		tx:                       tx,
		getItemFilePathStmt:      q.getItemFilePathStmt,
		getItemThumbnailPathStmt: q.getItemThumbnailPathStmt,
		insertItemStmt:           q.insertItemStmt,
		insertItemMetadataStmt:   q.insertItemMetadataStmt,
		insertSearchValueStmt:    q.insertSearchValueStmt,
		listItemsStmt:            q.listItemsStmt,
		searchStmt:               q.searchStmt,
		searchByTypeStmt:         q.searchByTypeStmt,
	}
}
