// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sql

import (
	"context"
	"database/sql"
	"fmt"
)

type DBTX interface {
	ExecContext(context.Context, string, ...interface{}) (sql.Result, error)
	PrepareContext(context.Context, string) (*sql.Stmt, error)
	QueryContext(context.Context, string, ...interface{}) (*sql.Rows, error)
	QueryRowContext(context.Context, string, ...interface{}) *sql.Row
}

func New(db DBTX) *Queries {
	return &Queries{db: db}
}

func Prepare(ctx context.Context, db DBTX) (*Queries, error) {
	q := Queries{db: db}
	var err error
	if q.countGroupItemsStmt, err = db.PrepareContext(ctx, countGroupItems); err != nil {
		return nil, fmt.Errorf("error preparing query CountGroupItems: %w", err)
	}
	if q.deleteGroupStmt, err = db.PrepareContext(ctx, deleteGroup); err != nil {
		return nil, fmt.Errorf("error preparing query DeleteGroup: %w", err)
	}
	if q.deleteItemStmt, err = db.PrepareContext(ctx, deleteItem); err != nil {
		return nil, fmt.Errorf("error preparing query DeleteItem: %w", err)
	}
	if q.deleteSearchValuesStmt, err = db.PrepareContext(ctx, deleteSearchValues); err != nil {
		return nil, fmt.Errorf("error preparing query DeleteSearchValues: %w", err)
	}
	if q.getGroupFilePathStmt, err = db.PrepareContext(ctx, getGroupFilePath); err != nil {
		return nil, fmt.Errorf("error preparing query GetGroupFilePath: %w", err)
	}
	if q.getGroupFilesStmt, err = db.PrepareContext(ctx, getGroupFiles); err != nil {
		return nil, fmt.Errorf("error preparing query GetGroupFiles: %w", err)
	}
	if q.getGroupIDStmt, err = db.PrepareContext(ctx, getGroupID); err != nil {
		return nil, fmt.Errorf("error preparing query GetGroupID: %w", err)
	}
	if q.getGroupInfoStmt, err = db.PrepareContext(ctx, getGroupInfo); err != nil {
		return nil, fmt.Errorf("error preparing query GetGroupInfo: %w", err)
	}
	if q.getGroupItemPathsStmt, err = db.PrepareContext(ctx, getGroupItemPaths); err != nil {
		return nil, fmt.Errorf("error preparing query GetGroupItemPaths: %w", err)
	}
	if q.getGroupItemsStmt, err = db.PrepareContext(ctx, getGroupItems); err != nil {
		return nil, fmt.Errorf("error preparing query GetGroupItems: %w", err)
	}
	if q.getGroupItemsWithMetadataStmt, err = db.PrepareContext(ctx, getGroupItemsWithMetadata); err != nil {
		return nil, fmt.Errorf("error preparing query GetGroupItemsWithMetadata: %w", err)
	}
	if q.getGroupThumbnailPathStmt, err = db.PrepareContext(ctx, getGroupThumbnailPath); err != nil {
		return nil, fmt.Errorf("error preparing query GetGroupThumbnailPath: %w", err)
	}
	if q.getItemByChecksumStmt, err = db.PrepareContext(ctx, getItemByChecksum); err != nil {
		return nil, fmt.Errorf("error preparing query GetItemByChecksum: %w", err)
	}
	if q.getItemFilePathStmt, err = db.PrepareContext(ctx, getItemFilePath); err != nil {
		return nil, fmt.Errorf("error preparing query GetItemFilePath: %w", err)
	}
	if q.getItemInfoStmt, err = db.PrepareContext(ctx, getItemInfo); err != nil {
		return nil, fmt.Errorf("error preparing query GetItemInfo: %w", err)
	}
	if q.getItemThumbnailPathStmt, err = db.PrepareContext(ctx, getItemThumbnailPath); err != nil {
		return nil, fmt.Errorf("error preparing query GetItemThumbnailPath: %w", err)
	}
	if q.getKVStmt, err = db.PrepareContext(ctx, getKV); err != nil {
		return nil, fmt.Errorf("error preparing query GetKV: %w", err)
	}
	if q.insertItemStmt, err = db.PrepareContext(ctx, insertItem); err != nil {
		return nil, fmt.Errorf("error preparing query InsertItem: %w", err)
	}
	if q.insertItemMetadataStmt, err = db.PrepareContext(ctx, insertItemMetadata); err != nil {
		return nil, fmt.Errorf("error preparing query InsertItemMetadata: %w", err)
	}
	if q.insertSearchValueStmt, err = db.PrepareContext(ctx, insertSearchValue); err != nil {
		return nil, fmt.Errorf("error preparing query InsertSearchValue: %w", err)
	}
	if q.listItemsStmt, err = db.PrepareContext(ctx, listItems); err != nil {
		return nil, fmt.Errorf("error preparing query ListItems: %w", err)
	}
	if q.searchStmt, err = db.PrepareContext(ctx, search); err != nil {
		return nil, fmt.Errorf("error preparing query Search: %w", err)
	}
	if q.searchByTypeStmt, err = db.PrepareContext(ctx, searchByType); err != nil {
		return nil, fmt.Errorf("error preparing query SearchByType: %w", err)
	}
	if q.updateGroupNameStmt, err = db.PrepareContext(ctx, updateGroupName); err != nil {
		return nil, fmt.Errorf("error preparing query UpdateGroupName: %w", err)
	}
	if q.updateItemStmt, err = db.PrepareContext(ctx, updateItem); err != nil {
		return nil, fmt.Errorf("error preparing query UpdateItem: %w", err)
	}
	if q.upsertGroupStmt, err = db.PrepareContext(ctx, upsertGroup); err != nil {
		return nil, fmt.Errorf("error preparing query UpsertGroup: %w", err)
	}
	if q.upsertKVStmt, err = db.PrepareContext(ctx, upsertKV); err != nil {
		return nil, fmt.Errorf("error preparing query UpsertKV: %w", err)
	}
	return &q, nil
}

func (q *Queries) Close() error {
	var err error
	if q.countGroupItemsStmt != nil {
		if cerr := q.countGroupItemsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing countGroupItemsStmt: %w", cerr)
		}
	}
	if q.deleteGroupStmt != nil {
		if cerr := q.deleteGroupStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing deleteGroupStmt: %w", cerr)
		}
	}
	if q.deleteItemStmt != nil {
		if cerr := q.deleteItemStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing deleteItemStmt: %w", cerr)
		}
	}
	if q.deleteSearchValuesStmt != nil {
		if cerr := q.deleteSearchValuesStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing deleteSearchValuesStmt: %w", cerr)
		}
	}
	if q.getGroupFilePathStmt != nil {
		if cerr := q.getGroupFilePathStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getGroupFilePathStmt: %w", cerr)
		}
	}
	if q.getGroupFilesStmt != nil {
		if cerr := q.getGroupFilesStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getGroupFilesStmt: %w", cerr)
		}
	}
	if q.getGroupIDStmt != nil {
		if cerr := q.getGroupIDStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getGroupIDStmt: %w", cerr)
		}
	}
	if q.getGroupInfoStmt != nil {
		if cerr := q.getGroupInfoStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getGroupInfoStmt: %w", cerr)
		}
	}
	if q.getGroupItemPathsStmt != nil {
		if cerr := q.getGroupItemPathsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getGroupItemPathsStmt: %w", cerr)
		}
	}
	if q.getGroupItemsStmt != nil {
		if cerr := q.getGroupItemsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getGroupItemsStmt: %w", cerr)
		}
	}
	if q.getGroupItemsWithMetadataStmt != nil {
		if cerr := q.getGroupItemsWithMetadataStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getGroupItemsWithMetadataStmt: %w", cerr)
		}
	}
	if q.getGroupThumbnailPathStmt != nil {
		if cerr := q.getGroupThumbnailPathStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getGroupThumbnailPathStmt: %w", cerr)
		}
	}
	if q.getItemByChecksumStmt != nil {
		if cerr := q.getItemByChecksumStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getItemByChecksumStmt: %w", cerr)
		}
	}
	if q.getItemFilePathStmt != nil {
		if cerr := q.getItemFilePathStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getItemFilePathStmt: %w", cerr)
		}
	}
	if q.getItemInfoStmt != nil {
		if cerr := q.getItemInfoStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getItemInfoStmt: %w", cerr)
		}
	}
	if q.getItemThumbnailPathStmt != nil {
		if cerr := q.getItemThumbnailPathStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getItemThumbnailPathStmt: %w", cerr)
		}
	}
	if q.getKVStmt != nil {
		if cerr := q.getKVStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getKVStmt: %w", cerr)
		}
	}
	if q.insertItemStmt != nil {
		if cerr := q.insertItemStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing insertItemStmt: %w", cerr)
		}
	}
	if q.insertItemMetadataStmt != nil {
		if cerr := q.insertItemMetadataStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing insertItemMetadataStmt: %w", cerr)
		}
	}
	if q.insertSearchValueStmt != nil {
		if cerr := q.insertSearchValueStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing insertSearchValueStmt: %w", cerr)
		}
	}
	if q.listItemsStmt != nil {
		if cerr := q.listItemsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listItemsStmt: %w", cerr)
		}
	}
	if q.searchStmt != nil {
		if cerr := q.searchStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing searchStmt: %w", cerr)
		}
	}
	if q.searchByTypeStmt != nil {
		if cerr := q.searchByTypeStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing searchByTypeStmt: %w", cerr)
		}
	}
	if q.updateGroupNameStmt != nil {
		if cerr := q.updateGroupNameStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing updateGroupNameStmt: %w", cerr)
		}
	}
	if q.updateItemStmt != nil {
		if cerr := q.updateItemStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing updateItemStmt: %w", cerr)
		}
	}
	if q.upsertGroupStmt != nil {
		if cerr := q.upsertGroupStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing upsertGroupStmt: %w", cerr)
		}
	}
	if q.upsertKVStmt != nil {
		if cerr := q.upsertKVStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing upsertKVStmt: %w", cerr)
		}
	}
	return err
}

func (q *Queries) exec(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) (sql.Result, error) {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).ExecContext(ctx, args...)
	case stmt != nil:
		return stmt.ExecContext(ctx, args...)
	default:
		return q.db.ExecContext(ctx, query, args...)
	}
}

func (q *Queries) query(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) (*sql.Rows, error) {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).QueryContext(ctx, args...)
	case stmt != nil:
		return stmt.QueryContext(ctx, args...)
	default:
		return q.db.QueryContext(ctx, query, args...)
	}
}

func (q *Queries) queryRow(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) *sql.Row {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).QueryRowContext(ctx, args...)
	case stmt != nil:
		return stmt.QueryRowContext(ctx, args...)
	default:
		return q.db.QueryRowContext(ctx, query, args...)
	}
}

type Queries struct {
	db                            DBTX
	tx                            *sql.Tx
	countGroupItemsStmt           *sql.Stmt
	deleteGroupStmt               *sql.Stmt
	deleteItemStmt                *sql.Stmt
	deleteSearchValuesStmt        *sql.Stmt
	getGroupFilePathStmt          *sql.Stmt
	getGroupFilesStmt             *sql.Stmt
	getGroupIDStmt                *sql.Stmt
	getGroupInfoStmt              *sql.Stmt
	getGroupItemPathsStmt         *sql.Stmt
	getGroupItemsStmt             *sql.Stmt
	getGroupItemsWithMetadataStmt *sql.Stmt
	getGroupThumbnailPathStmt     *sql.Stmt
	getItemByChecksumStmt         *sql.Stmt
	getItemFilePathStmt           *sql.Stmt
	getItemInfoStmt               *sql.Stmt
	getItemThumbnailPathStmt      *sql.Stmt
	getKVStmt                     *sql.Stmt
	insertItemStmt                *sql.Stmt
	insertItemMetadataStmt        *sql.Stmt
	insertSearchValueStmt         *sql.Stmt
	listItemsStmt                 *sql.Stmt
	searchStmt                    *sql.Stmt
	searchByTypeStmt              *sql.Stmt
	updateGroupNameStmt           *sql.Stmt
	updateItemStmt                *sql.Stmt
	upsertGroupStmt               *sql.Stmt
	upsertKVStmt                  *sql.Stmt
}

func (q *Queries) WithTx(tx *sql.Tx) *Queries {
	return &Queries{
		db:                            tx,
		tx:                            tx,
		countGroupItemsStmt:           q.countGroupItemsStmt,
		deleteGroupStmt:               q.deleteGroupStmt,
		deleteItemStmt:                q.deleteItemStmt,
		deleteSearchValuesStmt:        q.deleteSearchValuesStmt,
		getGroupFilePathStmt:          q.getGroupFilePathStmt,
		getGroupFilesStmt:             q.getGroupFilesStmt,
		getGroupIDStmt:                q.getGroupIDStmt,
		getGroupInfoStmt:              q.getGroupInfoStmt,
		getGroupItemPathsStmt:         q.getGroupItemPathsStmt,
		getGroupItemsStmt:             q.getGroupItemsStmt,
		getGroupItemsWithMetadataStmt: q.getGroupItemsWithMetadataStmt,
		getGroupThumbnailPathStmt:     q.getGroupThumbnailPathStmt,
		getItemByChecksumStmt:         q.getItemByChecksumStmt,
		getItemFilePathStmt:           q.getItemFilePathStmt,
		getItemInfoStmt:               q.getItemInfoStmt,
		getItemThumbnailPathStmt:      q.getItemThumbnailPathStmt,
		getKVStmt:                     q.getKVStmt,
		insertItemStmt:                q.insertItemStmt,
		insertItemMetadataStmt:        q.insertItemMetadataStmt,
		insertSearchValueStmt:         q.insertSearchValueStmt,
		listItemsStmt:                 q.listItemsStmt,
		searchStmt:                    q.searchStmt,
		searchByTypeStmt:              q.searchByTypeStmt,
		updateGroupNameStmt:           q.updateGroupNameStmt,
		updateItemStmt:                q.updateItemStmt,
		upsertGroupStmt:               q.upsertGroupStmt,
		upsertKVStmt:                  q.upsertKVStmt,
	}
}
