// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: get.sql

package sql

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const getItemFilePath = `-- name: GetItemFilePath :one
SELECT item_file_path
FROM   search_item
WHERE  item_id   = $1
AND    item_type = $2
`

type GetItemFilePathParams struct {
	ItemID   uuid.UUID    `db:"item_id"`
	ItemType ItemTypeEnum `db:"item_type"`
}

func (q *Queries) GetItemFilePath(ctx context.Context, arg GetItemFilePathParams) (string, error) {
	row := q.queryRow(ctx, q.getItemFilePathStmt, getItemFilePath, arg.ItemID, arg.ItemType)
	var item_file_path string
	err := row.Scan(&item_file_path)
	return item_file_path, err
}

const getItemThumbnailPath = `-- name: GetItemThumbnailPath :one
SELECT item_thumbnail_path
FROM   search_item
WHERE  item_id   = $1
AND    item_type = $2
AND    item_thumbnail_path IS NOT NULL
`

type GetItemThumbnailPathParams struct {
	ItemID   uuid.UUID    `db:"item_id"`
	ItemType ItemTypeEnum `db:"item_type"`
}

func (q *Queries) GetItemThumbnailPath(ctx context.Context, arg GetItemThumbnailPathParams) (sql.NullString, error) {
	row := q.queryRow(ctx, q.getItemThumbnailPathStmt, getItemThumbnailPath, arg.ItemID, arg.ItemType)
	var item_thumbnail_path sql.NullString
	err := row.Scan(&item_thumbnail_path)
	return item_thumbnail_path, err
}
