// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: insert.sql

package sql

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
	"github.com/sqlc-dev/pqtype"
)

const getGroupID = `-- name: GetGroupID :one
SELECT group_id
FROM   asset_group
WHERE  asset_type = $1
AND    group_name = $2
AND    group_key  = $3
`

type GetGroupIDParams struct {
	AssetType AssetTypeEnum `db:"asset_type"`
	GroupName string        `db:"group_name"`
	GroupKey  string        `db:"group_key"`
}

func (q *Queries) GetGroupID(ctx context.Context, arg GetGroupIDParams) (uuid.UUID, error) {
	row := q.queryRow(ctx, q.getGroupIDStmt, getGroupID, arg.AssetType, arg.GroupName, arg.GroupKey)
	var group_id uuid.UUID
	err := row.Scan(&group_id)
	return group_id, err
}

const insertItem = `-- name: InsertItem :execrows
INSERT INTO asset_item (item_id, group_id, group_value, size, checksum, item_file_path, item_thumbnail_path, thumbnail_checksum, original_filename)
SELECT $1, $2, $3, $4, $5, $6, $9, $7, $8
WHERE (SELECT total_size FROM storage_stats) + $4 <= $10
`

type InsertItemParams struct {
	ItemID            uuid.UUID      `db:"item_id"`
	GroupID           uuid.UUID      `db:"group_id"`
	GroupValue        string         `db:"group_value"`
	Size              int64          `db:"size"`
	Checksum          string         `db:"checksum"`
	ItemFilePath      string         `db:"item_file_path"`
	ThumbnailChecksum string         `db:"thumbnail_checksum"`
	OriginalFilename  string         `db:"original_filename"`
	ItemThumbnailPath sql.NullString `db:"item_thumbnail_path"`
	MaxTotalSize      int64          `db:"max_total_size"`
}

func (q *Queries) InsertItem(ctx context.Context, arg InsertItemParams) (int64, error) {
	result, err := q.exec(ctx, q.insertItemStmt, insertItem,
		arg.ItemID,
		arg.GroupID,
		arg.GroupValue,
		arg.Size,
		arg.Checksum,
		arg.ItemFilePath,
		arg.ThumbnailChecksum,
		arg.OriginalFilename,
		arg.ItemThumbnailPath,
		arg.MaxTotalSize,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const insertItemMetadata = `-- name: InsertItemMetadata :exec
INSERT INTO asset_item_metadata (
    item_id,
    creator_ip,
    creator_agent,
    accept_language,
    referer,
    content_type,
    request_id
) VALUES ($1, $2, $3, $4, $5, $6, $7)
`

type InsertItemMetadataParams struct {
	ItemID         uuid.UUID   `db:"item_id"`
	CreatorIp      pqtype.Inet `db:"creator_ip"`
	CreatorAgent   string      `db:"creator_agent"`
	AcceptLanguage string      `db:"accept_language"`
	Referer        string      `db:"referer"`
	ContentType    string      `db:"content_type"`
	RequestID      string      `db:"request_id"`
}

func (q *Queries) InsertItemMetadata(ctx context.Context, arg InsertItemMetadataParams) error {
	_, err := q.exec(ctx, q.insertItemMetadataStmt, insertItemMetadata,
		arg.ItemID,
		arg.CreatorIp,
		arg.CreatorAgent,
		arg.AcceptLanguage,
		arg.Referer,
		arg.ContentType,
		arg.RequestID,
	)
	return err
}

const insertSearchValue = `-- name: InsertSearchValue :exec
INSERT INTO search_value (group_id, key_name, key_value)
VALUES ($1, $2, $3)
ON CONFLICT DO NOTHING
`

type InsertSearchValueParams struct {
	GroupID  uuid.UUID `db:"group_id"`
	KeyName  string    `db:"key_name"`
	KeyValue string    `db:"key_value"`
}

func (q *Queries) InsertSearchValue(ctx context.Context, arg InsertSearchValueParams) error {
	_, err := q.exec(ctx, q.insertSearchValueStmt, insertSearchValue, arg.GroupID, arg.KeyName, arg.KeyValue)
	return err
}

const upsertGroup = `-- name: UpsertGroup :exec
INSERT INTO asset_group (group_id, asset_type, group_name, group_key)
VALUES ($1, $2, $3, $4)
ON CONFLICT (asset_type, group_name, group_key) DO NOTHING
`

type UpsertGroupParams struct {
	GroupID   uuid.UUID     `db:"group_id"`
	AssetType AssetTypeEnum `db:"asset_type"`
	GroupName string        `db:"group_name"`
	GroupKey  string        `db:"group_key"`
}

func (q *Queries) UpsertGroup(ctx context.Context, arg UpsertGroupParams) error {
	_, err := q.exec(ctx, q.upsertGroupStmt, upsertGroup,
		arg.GroupID,
		arg.AssetType,
		arg.GroupName,
		arg.GroupKey,
	)
	return err
}
