// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: insert.sql

package sql

import (
	"context"
	"database/sql"
	"encoding/json"

	"github.com/google/uuid"
	"github.com/sqlc-dev/pqtype"
)

const insertItem = `-- name: InsertItem :execrows
INSERT INTO search_item (item_id, item_type, size, checksum, item_file_path, item_thumbnail_path, item_value, original_filename)
SELECT $1, $2, $3, $4, $5, $8, $6, $7
WHERE (SELECT total_size FROM storage_stats) + $3 <= $9
`

type InsertItemParams struct {
	ItemID            uuid.UUID       `db:"item_id"`
	ItemType          ItemTypeEnum    `db:"item_type"`
	Size              int64           `db:"size"`
	Checksum          string          `db:"checksum"`
	ItemFilePath      string          `db:"item_file_path"`
	ItemValue         json.RawMessage `db:"item_value"`
	OriginalFilename  string          `db:"original_filename"`
	ItemThumbnailPath sql.NullString  `db:"item_thumbnail_path"`
	MaxTotalSize      int64           `db:"max_total_size"`
}

func (q *Queries) InsertItem(ctx context.Context, arg InsertItemParams) (int64, error) {
	result, err := q.exec(ctx, q.insertItemStmt, insertItem,
		arg.ItemID,
		arg.ItemType,
		arg.Size,
		arg.Checksum,
		arg.ItemFilePath,
		arg.ItemValue,
		arg.OriginalFilename,
		arg.ItemThumbnailPath,
		arg.MaxTotalSize,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const insertItemMetadata = `-- name: InsertItemMetadata :exec
INSERT INTO search_item_metadata (
    item_id,
    creator_ip,
    creator_agent,
    accept_language,
    referer,
    content_type,
    request_id
) VALUES ($1, $2, $3, $4, $5, $6, $7)
`

type InsertItemMetadataParams struct {
	ItemID         uuid.UUID   `db:"item_id"`
	CreatorIp      pqtype.Inet `db:"creator_ip"`
	CreatorAgent   string      `db:"creator_agent"`
	AcceptLanguage string      `db:"accept_language"`
	Referer        string      `db:"referer"`
	ContentType    string      `db:"content_type"`
	RequestID      string      `db:"request_id"`
}

func (q *Queries) InsertItemMetadata(ctx context.Context, arg InsertItemMetadataParams) error {
	_, err := q.exec(ctx, q.insertItemMetadataStmt, insertItemMetadata,
		arg.ItemID,
		arg.CreatorIp,
		arg.CreatorAgent,
		arg.AcceptLanguage,
		arg.Referer,
		arg.ContentType,
		arg.RequestID,
	)
	return err
}

const insertSearchValue = `-- name: InsertSearchValue :exec
INSERT INTO search_value (item_id, key_name, key_value)
VALUES ($1, $2, $3)
ON CONFLICT DO NOTHING
`

type InsertSearchValueParams struct {
	ItemID   uuid.UUID `db:"item_id"`
	KeyName  string    `db:"key_name"`
	KeyValue string    `db:"key_value"`
}

func (q *Queries) InsertSearchValue(ctx context.Context, arg InsertSearchValueParams) error {
	_, err := q.exec(ctx, q.insertSearchValueStmt, insertSearchValue, arg.ItemID, arg.KeyName, arg.KeyValue)
	return err
}
