// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: kv.sql

package sql

import (
	"context"
)

const getKV = `-- name: GetKV :one
SELECT value FROM kv_store WHERE key = $1
`

func (q *Queries) GetKV(ctx context.Context, key string) (string, error) {
	row := q.queryRow(ctx, q.getKVStmt, getKV, key)
	var value string
	err := row.Scan(&value)
	return value, err
}

const upsertKV = `-- name: UpsertKV :exec
INSERT INTO kv_store (key, value)
VALUES ($1, $2)
ON CONFLICT (key) DO UPDATE SET value = EXCLUDED.value
`

type UpsertKVParams struct {
	Key   string `db:"key"`
	Value string `db:"value"`
}

func (q *Queries) UpsertKV(ctx context.Context, arg UpsertKVParams) error {
	_, err := q.exec(ctx, q.upsertKVStmt, upsertKV, arg.Key, arg.Value)
	return err
}
