// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: list.sql

package sql

import (
	"context"
	"database/sql"
	"encoding/json"

	"github.com/google/uuid"
)

const listItems = `-- name: ListItems :many
SELECT
    si.item_id,
    si.item_type,
    si.item_value,
    COUNT(*) OVER () AS total_count
FROM search_item si
LEFT JOIN search_item_metadata sim ON si.item_id = sim.item_id
WHERE si.item_type = $1
  AND (
      $4::text IS NULL
      OR EXISTS (
          SELECT 1 FROM search_value sv
          WHERE sv.item_id = si.item_id
            AND sv.key_name = 'name'
            AND sv.key_value ILIKE '%' || $4::text || '%'
      )
  )
  AND (
      $5::text IS NULL
      OR EXISTS (
          SELECT 1 FROM search_value sv
          WHERE sv.item_id = si.item_id
            AND sv.key_name = 'creator'
            AND sv.key_value ILIKE '%' || $5::text || '%'
      )
  )
  AND (
      $6::text IS NULL
      OR EXISTS (
          SELECT 1 FROM search_value sv
          WHERE sv.item_id = si.item_id
            AND sv.key_name = 'license'
            AND sv.key_value = $6::text
      )
  )
ORDER BY
  CASE WHEN NOT $7::bool THEN
    CASE $8::text
      WHEN 'name'       THEN si.item_value->>'name'
      WHEN 'created_at' THEN to_char(COALESCE(sim.created_at, '1970-01-01'::timestamptz), 'YYYY-MM-DD"T"HH24:MI:SS.US"Z"')
      ELSE si.item_value->>'name'
    END
  END ASC,
  CASE WHEN $7::bool THEN
    CASE $8::text
      WHEN 'name'       THEN si.item_value->>'name'
      WHEN 'created_at' THEN to_char(COALESCE(sim.created_at, '1970-01-01'::timestamptz), 'YYYY-MM-DD"T"HH24:MI:SS.US"Z"')
      ELSE si.item_value->>'name'
    END
  END DESC,
  si.item_id ASC
LIMIT $2 OFFSET $3
`

type ListItemsParams struct {
	ItemType      ItemTypeEnum   `db:"item_type"`
	Limit         int32          `db:"limit"`
	Offset        int32          `db:"offset"`
	FilterName    sql.NullString `db:"filter_name"`
	FilterCreator sql.NullString `db:"filter_creator"`
	FilterLicense sql.NullString `db:"filter_license"`
	SortDesc      bool           `db:"sort_desc"`
	SortField     string         `db:"sort_field"`
}

type ListItemsRow struct {
	ItemID     uuid.UUID       `db:"item_id"`
	ItemType   ItemTypeEnum    `db:"item_type"`
	ItemValue  json.RawMessage `db:"item_value"`
	TotalCount int64           `db:"total_count"`
}

func (q *Queries) ListItems(ctx context.Context, arg ListItemsParams) ([]ListItemsRow, error) {
	rows, err := q.query(ctx, q.listItemsStmt, listItems,
		arg.ItemType,
		arg.Limit,
		arg.Offset,
		arg.FilterName,
		arg.FilterCreator,
		arg.FilterLicense,
		arg.SortDesc,
		arg.SortField,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListItemsRow{}
	for rows.Next() {
		var i ListItemsRow
		if err := rows.Scan(
			&i.ItemID,
			&i.ItemType,
			&i.ItemValue,
			&i.TotalCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
