// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: list.sql

package sql

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const listItems = `-- name: ListItems :many
SELECT
    ag.group_id,
    ag.asset_type,
    ag.group_name,
    ag.group_key,
    CAST(COALESCE(
        (SELECT string_agg(sv.key_value, ', ' ORDER BY sv.key_value)
         FROM search_value sv
         WHERE sv.group_id = ag.group_id AND sv.key_name = 'creators'),
        ''
    ) AS TEXT) AS creators,
    CAST(COALESCE(
        (SELECT sv2.key_value
         FROM search_value sv2
         WHERE sv2.group_id = ag.group_id AND sv2.key_name = 'license'
         LIMIT 1),
        ''
    ) AS TEXT) AS license,
    CAST(COALESCE(
        (SELECT string_agg(ai.item_id::text || ':' || ai.group_value, ',' ORDER BY ai.group_value)
         FROM asset_item ai
         WHERE ai.group_id = ag.group_id),
        ''
    ) AS TEXT) AS variants,
    COALESCE(
        (SELECT SUM(ai.size) FROM asset_item ai WHERE ai.group_id = ag.group_id),
        0
    )::BIGINT AS total_size,
    COALESCE(
        (SELECT MIN(sim.created_at) FROM asset_item ai JOIN asset_item_metadata sim ON ai.item_id = sim.item_id WHERE ai.group_id = ag.group_id),
        '1970-01-01'::timestamptz
    )::timestamptz AS created_at,
    COUNT(*) OVER () AS total_count
FROM asset_group ag
WHERE ag.asset_type = $1
  AND (
      $4::text IS NULL
      OR EXISTS (
          SELECT 1 FROM search_value sv
          WHERE sv.group_id = ag.group_id
            AND sv.key_name = 'name'
            AND sv.key_value ILIKE '%' || $4::text || '%'
      )
  )
  AND (
      $5::text IS NULL
      OR EXISTS (
          SELECT 1 FROM search_value sv
          WHERE sv.group_id = ag.group_id
            AND sv.key_name = 'creators'
            AND sv.key_value ILIKE '%' || $5::text || '%'
      )
  )
  AND (
      $6::text IS NULL
      OR EXISTS (
          SELECT 1 FROM search_value sv
          WHERE sv.group_id = ag.group_id
            AND sv.key_name = 'license'
            AND sv.key_value = $6::text
      )
  )
  AND (
      $7::text IS NULL
      OR to_char(COALESCE(
          (SELECT MIN(dfsim.created_at) FROM asset_item dfai JOIN asset_item_metadata dfsim ON dfai.item_id = dfsim.item_id WHERE dfai.group_id = ag.group_id),
          '1970-01-01'::timestamptz
      ), 'YYYY-MM-DD') = $7::text
  )
ORDER BY
  CASE WHEN NOT $8::bool THEN
    CASE $9::text
      WHEN 'name'       THEN ag.group_name
      WHEN 'creators'   THEN COALESCE(
          (SELECT string_agg(sv.key_value, ', ' ORDER BY sv.key_value)
           FROM search_value sv
           WHERE sv.group_id = ag.group_id AND sv.key_name = 'creators'),
          '')
      WHEN 'license'    THEN COALESCE(
          (SELECT sv.key_value FROM search_value sv
           WHERE sv.group_id = ag.group_id AND sv.key_name = 'license' LIMIT 1),
          '')
      WHEN 'size'       THEN lpad(cast(COALESCE(
          (SELECT SUM(ai.size) FROM asset_item ai WHERE ai.group_id = ag.group_id),
          0) as text), 20, '0')
      WHEN 'created_at' THEN to_char(COALESCE(
          (SELECT MIN(sim.created_at) FROM asset_item ai JOIN asset_item_metadata sim ON ai.item_id = sim.item_id WHERE ai.group_id = ag.group_id),
          '1970-01-01'::timestamptz
      ), 'YYYY-MM-DD"T"HH24:MI:SS.US"Z"')
      ELSE ag.group_name
    END
  END ASC,
  CASE WHEN $8::bool THEN
    CASE $9::text
      WHEN 'name'       THEN ag.group_name
      WHEN 'creators'   THEN COALESCE(
          (SELECT string_agg(sv.key_value, ', ' ORDER BY sv.key_value)
           FROM search_value sv
           WHERE sv.group_id = ag.group_id AND sv.key_name = 'creators'),
          '')
      WHEN 'license'    THEN COALESCE(
          (SELECT sv.key_value FROM search_value sv
           WHERE sv.group_id = ag.group_id AND sv.key_name = 'license' LIMIT 1),
          '')
      WHEN 'size'       THEN lpad(cast(COALESCE(
          (SELECT SUM(ai.size) FROM asset_item ai WHERE ai.group_id = ag.group_id),
          0) as text), 20, '0')
      WHEN 'created_at' THEN to_char(COALESCE(
          (SELECT MIN(sim.created_at) FROM asset_item ai JOIN asset_item_metadata sim ON ai.item_id = sim.item_id WHERE ai.group_id = ag.group_id),
          '1970-01-01'::timestamptz
      ), 'YYYY-MM-DD"T"HH24:MI:SS.US"Z"')
      ELSE ag.group_name
    END
  END DESC,
  CASE WHEN $10::text <> '' AND NOT $11::bool THEN
    CASE $10::text
      WHEN 'name'       THEN ag.group_name
      WHEN 'creators'   THEN COALESCE(
          (SELECT string_agg(sv.key_value, ', ' ORDER BY sv.key_value)
           FROM search_value sv
           WHERE sv.group_id = ag.group_id AND sv.key_name = 'creators'),
          '')
      WHEN 'license'    THEN COALESCE(
          (SELECT sv.key_value FROM search_value sv
           WHERE sv.group_id = ag.group_id AND sv.key_name = 'license' LIMIT 1),
          '')
      WHEN 'size'       THEN lpad(cast(COALESCE(
          (SELECT SUM(ai.size) FROM asset_item ai WHERE ai.group_id = ag.group_id),
          0) as text), 20, '0')
      WHEN 'created_at' THEN to_char(COALESCE(
          (SELECT MIN(sim.created_at) FROM asset_item ai JOIN asset_item_metadata sim ON ai.item_id = sim.item_id WHERE ai.group_id = ag.group_id),
          '1970-01-01'::timestamptz
      ), 'YYYY-MM-DD"T"HH24:MI:SS.US"Z"')
      ELSE NULL
    END
  END ASC,
  CASE WHEN $10::text <> '' AND $11::bool THEN
    CASE $10::text
      WHEN 'name'       THEN ag.group_name
      WHEN 'creators'   THEN COALESCE(
          (SELECT string_agg(sv.key_value, ', ' ORDER BY sv.key_value)
           FROM search_value sv
           WHERE sv.group_id = ag.group_id AND sv.key_name = 'creators'),
          '')
      WHEN 'license'    THEN COALESCE(
          (SELECT sv.key_value FROM search_value sv
           WHERE sv.group_id = ag.group_id AND sv.key_name = 'license' LIMIT 1),
          '')
      WHEN 'size'       THEN lpad(cast(COALESCE(
          (SELECT SUM(ai.size) FROM asset_item ai WHERE ai.group_id = ag.group_id),
          0) as text), 20, '0')
      WHEN 'created_at' THEN to_char(COALESCE(
          (SELECT MIN(sim.created_at) FROM asset_item ai JOIN asset_item_metadata sim ON ai.item_id = sim.item_id WHERE ai.group_id = ag.group_id),
          '1970-01-01'::timestamptz
      ), 'YYYY-MM-DD"T"HH24:MI:SS.US"Z"')
      ELSE NULL
    END
  END DESC,
  ag.group_id ASC
LIMIT $2 OFFSET $3
`

type ListItemsParams struct {
	AssetType     AssetTypeEnum `db:"asset_type"`
	Limit         int32         `db:"limit"`
	Offset        int32         `db:"offset"`
	FilterName    *string       `db:"filter_name"`
	FilterCreator *string       `db:"filter_creator"`
	FilterLicense *string       `db:"filter_license"`
	FilterDate    *string       `db:"filter_date"`
	SortDesc      bool          `db:"sort_desc"`
	SortField     string        `db:"sort_field"`
	SortField2    string        `db:"sort_field_2"`
	SortDesc2     bool          `db:"sort_desc_2"`
}

type ListItemsRow struct {
	GroupID    pgtype.UUID        `db:"group_id"`
	AssetType  AssetTypeEnum      `db:"asset_type"`
	GroupName  string             `db:"group_name"`
	GroupKey   string             `db:"group_key"`
	Creators   string             `db:"creators"`
	License    string             `db:"license"`
	Variants   string             `db:"variants"`
	TotalSize  int64              `db:"total_size"`
	CreatedAt  pgtype.Timestamptz `db:"created_at"`
	TotalCount int64              `db:"total_count"`
}

func (q *Queries) ListItems(ctx context.Context, arg ListItemsParams) ([]ListItemsRow, error) {
	rows, err := q.db.Query(ctx, listItems,
		arg.AssetType,
		arg.Limit,
		arg.Offset,
		arg.FilterName,
		arg.FilterCreator,
		arg.FilterLicense,
		arg.FilterDate,
		arg.SortDesc,
		arg.SortField,
		arg.SortField2,
		arg.SortDesc2,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListItemsRow{}
	for rows.Next() {
		var i ListItemsRow
		if err := rows.Scan(
			&i.GroupID,
			&i.AssetType,
			&i.GroupName,
			&i.GroupKey,
			&i.Creators,
			&i.License,
			&i.Variants,
			&i.TotalSize,
			&i.CreatedAt,
			&i.TotalCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
