// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sql

import (
	"database/sql"
	"database/sql/driver"
	"encoding/json"
	"fmt"
	"time"

	"github.com/google/uuid"
	"github.com/sqlc-dev/pqtype"
)

type ItemTypeEnum string

const (
	ItemTypeEnumMap      ItemTypeEnum = "map"
	ItemTypeEnumGameskin ItemTypeEnum = "gameskin"
	ItemTypeEnumHud      ItemTypeEnum = "hud"
	ItemTypeEnumSkin     ItemTypeEnum = "skin"
	ItemTypeEnumEntity   ItemTypeEnum = "entity"
	ItemTypeEnumTheme    ItemTypeEnum = "theme"
	ItemTypeEnumTemplate ItemTypeEnum = "template"
	ItemTypeEnumEmoticon ItemTypeEnum = "emoticon"
)

func (e *ItemTypeEnum) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ItemTypeEnum(s)
	case string:
		*e = ItemTypeEnum(s)
	default:
		return fmt.Errorf("unsupported scan type for ItemTypeEnum: %T", src)
	}
	return nil
}

type NullItemTypeEnum struct {
	ItemTypeEnum ItemTypeEnum
	Valid        bool // Valid is true if ItemTypeEnum is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullItemTypeEnum) Scan(value interface{}) error {
	if value == nil {
		ns.ItemTypeEnum, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ItemTypeEnum.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullItemTypeEnum) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ItemTypeEnum), nil
}

func (e ItemTypeEnum) Valid() bool {
	switch e {
	case ItemTypeEnumMap,
		ItemTypeEnumGameskin,
		ItemTypeEnumHud,
		ItemTypeEnumSkin,
		ItemTypeEnumEntity,
		ItemTypeEnumTheme,
		ItemTypeEnumTemplate,
		ItemTypeEnumEmoticon:
		return true
	}
	return false
}

func AllItemTypeEnumValues() []ItemTypeEnum {
	return []ItemTypeEnum{
		ItemTypeEnumMap,
		ItemTypeEnumGameskin,
		ItemTypeEnumHud,
		ItemTypeEnumSkin,
		ItemTypeEnumEntity,
		ItemTypeEnumTheme,
		ItemTypeEnumTemplate,
		ItemTypeEnumEmoticon,
	}
}

type SearchItem struct {
	ItemID            uuid.UUID       `db:"item_id"`
	ItemType          ItemTypeEnum    `db:"item_type"`
	Size              int64           `db:"size"`
	Checksum          string          `db:"checksum"`
	ItemFilePath      string          `db:"item_file_path"`
	ItemThumbnailPath sql.NullString  `db:"item_thumbnail_path"`
	ItemValue         json.RawMessage `db:"item_value"`
	OriginalFilename  string          `db:"original_filename"`
}

type SearchItemMetadatum struct {
	ItemID         uuid.UUID   `db:"item_id"`
	CreatedAt      time.Time   `db:"created_at"`
	CreatorIp      pqtype.Inet `db:"creator_ip"`
	CreatorAgent   string      `db:"creator_agent"`
	AcceptLanguage string      `db:"accept_language"`
	Referer        string      `db:"referer"`
	ContentType    string      `db:"content_type"`
	RequestID      string      `db:"request_id"`
}

type SearchValue struct {
	ItemID   uuid.UUID `db:"item_id"`
	KeyName  string    `db:"key_name"`
	KeyValue string    `db:"key_value"`
}

type SearchValueWeight struct {
	KeyName string          `db:"key_name"`
	Weight  sql.NullFloat64 `db:"weight"`
}

type StorageStat struct {
	ID        bool  `db:"id"`
	TotalSize int64 `db:"total_size"`
}
