// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sql

import (
	"database/sql/driver"
	"fmt"
	"net/netip"

	"github.com/jackc/pgx/v5/pgtype"
)

type AssetTypeEnum string

const (
	AssetTypeEnumMap      AssetTypeEnum = "map"
	AssetTypeEnumGameskin AssetTypeEnum = "gameskin"
	AssetTypeEnumHud      AssetTypeEnum = "hud"
	AssetTypeEnumSkin     AssetTypeEnum = "skin"
	AssetTypeEnumEntity   AssetTypeEnum = "entity"
	AssetTypeEnumTheme    AssetTypeEnum = "theme"
	AssetTypeEnumTemplate AssetTypeEnum = "template"
	AssetTypeEnumEmoticon AssetTypeEnum = "emoticon"
)

func (e *AssetTypeEnum) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = AssetTypeEnum(s)
	case string:
		*e = AssetTypeEnum(s)
	default:
		return fmt.Errorf("unsupported scan type for AssetTypeEnum: %T", src)
	}
	return nil
}

type NullAssetTypeEnum struct {
	AssetTypeEnum AssetTypeEnum
	Valid         bool // Valid is true if AssetTypeEnum is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullAssetTypeEnum) Scan(value interface{}) error {
	if value == nil {
		ns.AssetTypeEnum, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.AssetTypeEnum.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullAssetTypeEnum) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.AssetTypeEnum), nil
}

func (e AssetTypeEnum) Valid() bool {
	switch e {
	case AssetTypeEnumMap,
		AssetTypeEnumGameskin,
		AssetTypeEnumHud,
		AssetTypeEnumSkin,
		AssetTypeEnumEntity,
		AssetTypeEnumTheme,
		AssetTypeEnumTemplate,
		AssetTypeEnumEmoticon:
		return true
	}
	return false
}

func AllAssetTypeEnumValues() []AssetTypeEnum {
	return []AssetTypeEnum{
		AssetTypeEnumMap,
		AssetTypeEnumGameskin,
		AssetTypeEnumHud,
		AssetTypeEnumSkin,
		AssetTypeEnumEntity,
		AssetTypeEnumTheme,
		AssetTypeEnumTemplate,
		AssetTypeEnumEmoticon,
	}
}

type AssetGroup struct {
	GroupID   pgtype.UUID   `db:"group_id"`
	AssetType AssetTypeEnum `db:"asset_type"`
	GroupName string        `db:"group_name"`
	GroupKey  string        `db:"group_key"`
}

type AssetItem struct {
	GroupID           pgtype.UUID `db:"group_id"`
	ItemID            pgtype.UUID `db:"item_id"`
	GroupValue        string      `db:"group_value"`
	Size              int64       `db:"size"`
	Checksum          string      `db:"checksum"`
	ItemFilePath      string      `db:"item_file_path"`
	ItemThumbnailPath *string     `db:"item_thumbnail_path"`
	ThumbnailChecksum string      `db:"thumbnail_checksum"`
	OriginalFilename  string      `db:"original_filename"`
}

type AssetItemMetadatum struct {
	ItemID         pgtype.UUID        `db:"item_id"`
	CreatedAt      pgtype.Timestamptz `db:"created_at"`
	CreatorIp      netip.Addr         `db:"creator_ip"`
	CreatorAgent   string             `db:"creator_agent"`
	AcceptLanguage string             `db:"accept_language"`
	Referer        string             `db:"referer"`
	ContentType    string             `db:"content_type"`
	RequestID      string             `db:"request_id"`
}

type SearchValue struct {
	GroupID  pgtype.UUID `db:"group_id"`
	KeyName  string      `db:"key_name"`
	KeyValue string      `db:"key_value"`
}

type SearchValueWeight struct {
	KeyName string   `db:"key_name"`
	Weight  *float32 `db:"weight"`
}

type StorageStat struct {
	ID        bool  `db:"id"`
	TotalSize int64 `db:"total_size"`
}
