// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: search.sql

package sql

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const search = `-- name: Search :many
SELECT
    ag.group_id,
    ag.asset_type,
    ag.group_name,
    ag.group_key,
    CAST(COALESCE(
        (SELECT string_agg(sv2.key_value, ', ' ORDER BY sv2.key_value)
         FROM search_value sv2
         WHERE sv2.group_id = ag.group_id AND sv2.key_name = 'creators'),
        ''
    ) AS TEXT) AS creators,
    CAST(COALESCE(
        (SELECT sv3.key_value
         FROM search_value sv3
         WHERE sv3.group_id = ag.group_id AND sv3.key_name = 'license'
         LIMIT 1),
        ''
    ) AS TEXT) AS license,
    CAST(COALESCE(
        (SELECT string_agg(ai.item_id::text || ':' || ai.group_value, ',' ORDER BY ai.group_value)
         FROM asset_item ai
         WHERE ai.group_id = ag.group_id),
        ''
    ) AS TEXT) AS variants,
    sm.sml,
    COUNT(*) OVER () AS total_count
FROM asset_group ag
JOIN (
    SELECT
        sv.group_id,
        CAST(
            SUM(strict_word_similarity(sv.key_value, $1) + COALESCE(sw.weight, 0))
            AS FLOAT8
        ) AS sml
    FROM  search_value sv
    LEFT JOIN search_value_weight sw ON sv.key_name = sw.key_name
    WHERE (length($1) >= 3 AND key_value ~* $1)
       OR (length($1) <  3 AND sv.key_name <> 'license' AND lower(key_value) LIKE '%' || lower($1) || '%')
    GROUP BY sv.group_id
) AS sm ON ag.group_id = sm.group_id
ORDER BY sm.sml DESC
LIMIT $2 OFFSET $3
`

type SearchParams struct {
	StrictWordSimilarity string `db:"strict_word_similarity"`
	Limit                int32  `db:"limit"`
	Offset               int32  `db:"offset"`
}

type SearchRow struct {
	GroupID    uuid.UUID     `db:"group_id"`
	AssetType  AssetTypeEnum `db:"asset_type"`
	GroupName  string        `db:"group_name"`
	GroupKey   string        `db:"group_key"`
	Creators   string        `db:"creators"`
	License    string        `db:"license"`
	Variants   string        `db:"variants"`
	Sml        float64       `db:"sml"`
	TotalCount int64         `db:"total_count"`
}

func (q *Queries) Search(ctx context.Context, arg SearchParams) ([]SearchRow, error) {
	rows, err := q.query(ctx, q.searchStmt, search, arg.StrictWordSimilarity, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SearchRow{}
	for rows.Next() {
		var i SearchRow
		if err := rows.Scan(
			&i.GroupID,
			&i.AssetType,
			&i.GroupName,
			&i.GroupKey,
			&i.Creators,
			&i.License,
			&i.Variants,
			&i.Sml,
			&i.TotalCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchByType = `-- name: SearchByType :many
SELECT
    ag.group_id,
    ag.asset_type,
    ag.group_name,
    ag.group_key,
    CAST(COALESCE(
        (SELECT string_agg(sv2.key_value, ', ' ORDER BY sv2.key_value)
         FROM search_value sv2
         WHERE sv2.group_id = ag.group_id AND sv2.key_name = 'creators'),
        ''
    ) AS TEXT) AS creators,
    CAST(COALESCE(
        (SELECT sv3.key_value
         FROM search_value sv3
         WHERE sv3.group_id = ag.group_id AND sv3.key_name = 'license'
         LIMIT 1),
        ''
    ) AS TEXT) AS license,
    CAST(COALESCE(
        (SELECT string_agg(ai.item_id::text || ':' || ai.group_value, ',' ORDER BY ai.group_value)
         FROM asset_item ai
         WHERE ai.group_id = ag.group_id),
        ''
    ) AS TEXT) AS variants,
    COALESCE(
        (SELECT SUM(ai.size) FROM asset_item ai WHERE ai.group_id = ag.group_id),
        0
    )::BIGINT AS total_size,
    COALESCE(
        (SELECT MIN(sim.created_at) FROM asset_item ai JOIN asset_item_metadata sim ON ai.item_id = sim.item_id WHERE ai.group_id = ag.group_id),
        '1970-01-01'::timestamptz
    )::timestamptz AS created_at,
    sm.sml,
    COUNT(*) OVER () AS total_count
FROM asset_group ag
JOIN (
    SELECT
        sv.group_id,
        CAST(
            SUM(strict_word_similarity(sv.key_value, $1) + COALESCE(sw.weight, 0))
            AS FLOAT8
        ) AS sml
    FROM  search_value sv
    LEFT JOIN search_value_weight sw ON sv.key_name = sw.key_name
    WHERE (length($1) >= 3 AND key_value ~* $1)
       OR (length($1) <  3 AND sv.key_name <> 'license' AND lower(key_value) LIKE '%' || lower($1) || '%')
    GROUP BY sv.group_id
) AS sm ON ag.group_id = sm.group_id
WHERE ag.asset_type = $4
ORDER BY
  CASE WHEN $5::text = '' THEN NULL END,
  CASE WHEN $5::text <> '' AND NOT $6::bool THEN
    CASE $5::text
      WHEN 'name'       THEN ag.group_name
      WHEN 'creators'   THEN COALESCE(
          (SELECT string_agg(sv3.key_value, ', ' ORDER BY sv3.key_value)
           FROM search_value sv3
           WHERE sv3.group_id = ag.group_id AND sv3.key_name = 'creators'),
          '')
      WHEN 'size'       THEN lpad(cast(COALESCE(
          (SELECT SUM(ai.size) FROM asset_item ai WHERE ai.group_id = ag.group_id),
          0) as text), 20, '0')
      WHEN 'created_at' THEN to_char(COALESCE(
          (SELECT MIN(sim.created_at) FROM asset_item ai JOIN asset_item_metadata sim ON ai.item_id = sim.item_id WHERE ai.group_id = ag.group_id),
          '1970-01-01'::timestamptz
      ), 'YYYY-MM-DD"T"HH24:MI:SS.US"Z"')
      ELSE NULL
    END
  END ASC,
  CASE WHEN $5::text <> '' AND $6::bool THEN
    CASE $5::text
      WHEN 'name'       THEN ag.group_name
      WHEN 'creators'   THEN COALESCE(
          (SELECT string_agg(sv3.key_value, ', ' ORDER BY sv3.key_value)
           FROM search_value sv3
           WHERE sv3.group_id = ag.group_id AND sv3.key_name = 'creators'),
          '')
      WHEN 'size'       THEN lpad(cast(COALESCE(
          (SELECT SUM(ai.size) FROM asset_item ai WHERE ai.group_id = ag.group_id),
          0) as text), 20, '0')
      WHEN 'created_at' THEN to_char(COALESCE(
          (SELECT MIN(sim.created_at) FROM asset_item ai JOIN asset_item_metadata sim ON ai.item_id = sim.item_id WHERE ai.group_id = ag.group_id),
          '1970-01-01'::timestamptz
      ), 'YYYY-MM-DD"T"HH24:MI:SS.US"Z"')
      ELSE NULL
    END
  END DESC,
  sm.sml DESC
LIMIT $2 OFFSET $3
`

type SearchByTypeParams struct {
	StrictWordSimilarity string        `db:"strict_word_similarity"`
	Limit                int32         `db:"limit"`
	Offset               int32         `db:"offset"`
	AssetType            AssetTypeEnum `db:"asset_type"`
	SortField            string        `db:"sort_field"`
	SortDesc             bool          `db:"sort_desc"`
}

type SearchByTypeRow struct {
	GroupID    uuid.UUID     `db:"group_id"`
	AssetType  AssetTypeEnum `db:"asset_type"`
	GroupName  string        `db:"group_name"`
	GroupKey   string        `db:"group_key"`
	Creators   string        `db:"creators"`
	License    string        `db:"license"`
	Variants   string        `db:"variants"`
	TotalSize  int64         `db:"total_size"`
	CreatedAt  time.Time     `db:"created_at"`
	Sml        float64       `db:"sml"`
	TotalCount int64         `db:"total_count"`
}

func (q *Queries) SearchByType(ctx context.Context, arg SearchByTypeParams) ([]SearchByTypeRow, error) {
	rows, err := q.query(ctx, q.searchByTypeStmt, searchByType,
		arg.StrictWordSimilarity,
		arg.Limit,
		arg.Offset,
		arg.AssetType,
		arg.SortField,
		arg.SortDesc,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SearchByTypeRow{}
	for rows.Next() {
		var i SearchByTypeRow
		if err := rows.Scan(
			&i.GroupID,
			&i.AssetType,
			&i.GroupName,
			&i.GroupKey,
			&i.Creators,
			&i.License,
			&i.Variants,
			&i.TotalSize,
			&i.CreatedAt,
			&i.Sml,
			&i.TotalCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
