// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: search.sql

package sql

import (
	"context"
	"encoding/json"

	"github.com/google/uuid"
)

const search = `-- name: Search :many
SELECT
    sm.item_id,
    si.item_type,
    sm.sml,
    si.item_value,
    COUNT(*) OVER () AS total_count
FROM search_item si
JOIN (
    SELECT
        sv.item_id,
        CAST(
            SUM(strict_word_similarity(sv.key_value, $1) + COALESCE(sw.weight, 0))
            AS FLOAT8
        ) AS sml
    FROM  search_value sv
    LEFT JOIN search_value_weight sw ON sv.key_name = sw.key_name
    WHERE key_value ~* $1 -- search keywords
    GROUP BY sv.item_id
) AS sm ON si.item_id = sm.item_id
ORDER BY sm.sml DESC
LIMIT $2 OFFSET $3
`

type SearchParams struct {
	StrictWordSimilarity string `db:"strict_word_similarity"`
	Limit                int32  `db:"limit"`
	Offset               int32  `db:"offset"`
}

type SearchRow struct {
	ItemID     uuid.UUID       `db:"item_id"`
	ItemType   ItemTypeEnum    `db:"item_type"`
	Sml        float64         `db:"sml"`
	ItemValue  json.RawMessage `db:"item_value"`
	TotalCount int64           `db:"total_count"`
}

func (q *Queries) Search(ctx context.Context, arg SearchParams) ([]SearchRow, error) {
	rows, err := q.query(ctx, q.searchStmt, search, arg.StrictWordSimilarity, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SearchRow{}
	for rows.Next() {
		var i SearchRow
		if err := rows.Scan(
			&i.ItemID,
			&i.ItemType,
			&i.Sml,
			&i.ItemValue,
			&i.TotalCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchByType = `-- name: SearchByType :many
SELECT
    sm.item_id,
    si.item_type,
    sm.sml,
    si.item_value,
    COUNT(*) OVER () AS total_count
FROM search_item si
JOIN (
    SELECT
        sv.item_id,
        CAST(
            SUM(strict_word_similarity(sv.key_value, $1) + COALESCE(sw.weight, 0))
            AS FLOAT8
        ) AS sml
    FROM  search_value sv
    LEFT JOIN search_value_weight sw ON sv.key_name = sw.key_name
    WHERE key_value ~* $1 -- search keywords
    GROUP BY sv.item_id
) AS sm ON si.item_id = sm.item_id
WHERE si.item_type = $4
ORDER BY sm.sml DESC
LIMIT $2 OFFSET $3
`

type SearchByTypeParams struct {
	StrictWordSimilarity string       `db:"strict_word_similarity"`
	Limit                int32        `db:"limit"`
	Offset               int32        `db:"offset"`
	ItemType             ItemTypeEnum `db:"item_type"`
}

type SearchByTypeRow struct {
	ItemID     uuid.UUID       `db:"item_id"`
	ItemType   ItemTypeEnum    `db:"item_type"`
	Sml        float64         `db:"sml"`
	ItemValue  json.RawMessage `db:"item_value"`
	TotalCount int64           `db:"total_count"`
}

func (q *Queries) SearchByType(ctx context.Context, arg SearchByTypeParams) ([]SearchByTypeRow, error) {
	rows, err := q.query(ctx, q.searchByTypeStmt, searchByType,
		arg.StrictWordSimilarity,
		arg.Limit,
		arg.Offset,
		arg.ItemType,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SearchByTypeRow{}
	for rows.Next() {
		var i SearchByTypeRow
		if err := rows.Scan(
			&i.ItemID,
			&i.ItemType,
			&i.Sml,
			&i.ItemValue,
			&i.TotalCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
